@component('mail::message')
# Dear {{ $content['name'] }}, <br>



Your payment is approved , check your portal to verify <br>
You can login with you email address (ID) and Password<br>
<br>
<br>


If you have any questions, please contact us.<br>
{{ config('app.name') }}

<br>
<br>
<br>
<br>
<br>
Automatically generated by System. PLEASE DO NOT REPLY
@endcomponent
